
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=/workspace/envs/.env.prod.enc
      - --plaintext-file=/workspace/.env
      - --location=global
      - --keyring=aang-envs
      - --key=key-envs
      - --verbosity=debug
  - name: gcr.io/cloud-builders/npm
    args: ["install"]
  - name: gcr.io/cloud-builders/npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/avatar-419000/github.com/fjborquez/katara-back:$SHORT_SHA",
        "-t",
        "gcr.io/avatar-419000/github.com/fjborquez/katara-back:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/avatar-419000/github.com/fjborquez/katara-back:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/avatar-419000/github.com/fjborquez/katara-back:latest",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "katara-back",
        "--image",
        "gcr.io/avatar-419000/github.com/fjborquez/katara-back:$SHORT_SHA",
        "--region",
        "southamerica-east1",
        "--platform",
        "managed",
        "--verbosity",
        "debug",
        "--memory",
        "256Mi",
        "--cpu",
        "2000m",
        "--port",
        "8080",
        "--timeout",
        "3600",
        "--min-instances",
        "0",
      ]
    env:
      - "PORT=8080"
images:
  - gcr.io/avatar-419000/github.com/fjborquez/katara-back:$SHORT_SHA
  - gcr.io/avatar-419000/github.com/fjborquez/katara-back:latest
timeout: 2400s
